name: Test if we can commit to the repo from CI

on:
    push:
        branches: [ test-gh-token ]

jobs:
    test:
        name: Test if we can commit to the repo from CI
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    token: ${{ secrets.GH_TOKEN }}
                    fetch-depth: 0 # we need to pull everything to allow lerna to detect what packages changed
                    ref: master
            -   uses: actions/setup-node@v2
                with:
                    node-version: 14
            -   name: Release
                run: |
                    git config --global user.name 'Apify Release Bot'
                    git config --global user.email 'noreply@apify.com'
                    echo '123' > test.txt
                    git commit -am 'chore: verify we can commit to master via CI [skip ci]'
                    git push
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                    GIT_USER: "noreply@apify.com:${{ secrets.GH_TOKEN }}"
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
